export const services = [
  {
    slug: "emergency-response",
    icon: "Zap",
    title: "Emergency Response",
    tagline: "First on scene, every time",
    desc: "Rapid dispatch for accidents, cardiac events, and life-threatening emergencies. Our nearest available unit is routed to you the moment you call.",
    features: [
      "Average dispatch time under 9 minutes",
      "First-responder trained paramedic crew",
      "Direct line to the nearest trauma centre",
      "GPS-tracked, live ETA updates",
    ],
    responseTime: "8-10 min",
  },
  {
    slug: "icu-on-wheels",
    icon: "HeartPulse",
    title: "ICU on Wheels",
    tagline: "Critical care, in transit",
    desc: "Fully equipped mobile ICU for critically ill patients who need continuous monitoring and life support during transport between hospitals.",
    features: [
      "Ventilator and cardiac monitor onboard",
      "Defibrillator and emergency drug kit",
      "ICU-trained nursing staff",
      "Oxygen backup for extended transfers",
    ],
    responseTime: "15-20 min",
  },
  {
    slug: "patient-transfer",
    icon: "Truck",
    title: "Patient Transfer",
    tagline: "Scheduled, comfortable, on time",
    desc: "Non-emergency transport between hospitals, clinics, diagnostic centres, or home — booked in advance for a stress-free journey.",
    features: [
      "Advance booking with confirmed time slot",
      "Wheelchair and stretcher accessible",
      "Trained attendant accompanies patient",
      "Fixed, transparent pricing",
    ],
    responseTime: "Scheduled",
  },
  {
    slug: "event-standby",
    icon: "Users",
    title: "Event & Standby Cover",
    tagline: "Ready before anything happens",
    desc: "On-site ambulance and paramedic standby for weddings, sports events, corporate gatherings, and film shoots.",
    features: [
      "Dedicated ambulance parked on-site",
      "Paramedic present for full event duration",
      "Basic first-aid station setup",
      "Custom coverage duration and headcount",
    ],
    responseTime: "On-site",
  },
  {
    slug: "home-care-pickup",
    icon: "Home",
    title: "Home Care Pickup",
    tagline: "Gentle care from your doorstep",
    desc: "Careful stretcher transport for elderly, bedridden, or post-surgery patients travelling between home and hospital.",
    features: [
      "Trained staff for safe lifting and transfer",
      "Comfortable stretcher and cushioned support",
      "Family member can accompany the patient",
      "Available for short and long-distance trips",
    ],
    responseTime: "20-30 min",
  },
  {
    slug: "mortuary-transport",
    icon: "Flower2",
    title: "Mortuary Transport",
    tagline: "Handled with dignity",
    desc: "Respectful, dignified transport service available around the clock for families during a difficult time.",
    features: [
      "Available 24/7, including holidays",
      "Discreet, dedicated mortuary vehicle",
      "Coordination with hospital and crematorium",
      "Compassionate, trained staff",
    ],
    responseTime: "Available 24/7",
  },
];
